---
- name: "Five minutes event rules"
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 300
        delay: 1  # 300 seconds
  rules:
    - name: Five hundred events rule
      condition: >-
        event.i in [
          0, 10, 20, 30, 40, 50,
          60, 70, 80, 90, 100, 110,
          120, 130, 140, 150, 160, 170,
          180, 190, 200, 210, 220, 230,
          240, 250, 260, 270, 280, 290,
          300
        ]
      action:
        debug:
          msg: "Event {{ event.i }} triggered"
