---
- name: Long Running Range
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 300 # 2 years
        delay: 1
  rules:
    - name: Say Hello long running
      # Gap increases exponentially the first day
      # then increases linearly after that
      # one time per day the first month
      # after one time per month.
      condition: >-
        event.i in [5, 30, 60]
        or event.i in [90,
                       120,
                       150,
                       180]
      action:
        debug:
          msg: "Hello World!, event.i = {{ event.i }}"
